package io.delimeat.core.feed;

public enum FeedResultRejection {

	INCORRECT_TITLE,
	INVALID_SEASON_RESULT,
	INVALID_MINI_SERIES_RESULT,
	INVALID_DAILY_RESULT,
	CONTAINS_FOLDERS,
	CONTAINS_COMPRESSED,
	CONTAINS_EXCLUDED_FILE_TYPES,
	FILE_SIZE_INCORRECT,
	INSUFFICENT_SEEDERS
}
