package io.delimeat.core.feed;

public enum FeedResultRejection {

	INCORRECT_TITLE,
	NOT_A_SEASON_EPISODE,
	INCORRECT_SEASON,
	INCORRECT_EPISODE,
	NOT_A_MINI_SERIES_EPISODE,
	NOT_A_DAILY_EPISODE,
	INCORRECT_DAILY_EPISODE
}
