package io.delimeat.core.feed;

public enum TorrentRejection {

	CONTAINS_FOLDERS,
	CONTAINS_COMPRESSED,
	CONTAINS_EXCLUDED_FILE_TYPES,
	FILE_SIZE_INCORRECT,
	UNNABLE_TO_GET_TORRENT,
	INSUFFICENT_SEEDERS
}
