package io.delimeat.util.jaxb;

import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class TvdbTimezoneAdapter extends XmlAdapter<String, String> {

	@Override
	public String marshal(String value) throws Exception {
		return null;
	}

	@Override
	public String unmarshal(String value) throws Exception {
		if(value==null || "".equals(value)){
			return null;
		}
		return LIST.containsKey(value) ? LIST.get(value) : "EST";
	}
	
	public static final Map<String,String> LIST = new HashMap<String,String>() {
		private static final long serialVersionUID = 1L;

		{
	    	put("Televisa","CST");
	    	put("TV Azteca","CST");
	    	put("TV Chile","Chile/Continental");
	    	put("Record","BET");
	    	put("Rede Globo","BET");
	    	put("Setanta Ireland","Europe/Belfast");
	    	put("Bubble Hits","Europe/Belfast");
	    	put("Channel 6","Europe/Belfast");
	    	put("Chorus Sports","Europe/Belfast");
	    	put("City Channel","Europe/Belfast");
	    	put("E4","Europe/Belfast");
	    	put("RTÉ One","Europe/Belfast");
	    	put("RTÉ Two","Europe/Belfast");
	    	put("Sky News Ireland","Europe/Belfast");
	    	put("The Den","Europe/Belfast");
	    	put("UTV","Europe/Belfast");
	    	put("PRO TV","CET");
	    	put("STV","GMT");
	    	put("TeleG","GMT");
	    	put("Adult Channel","Europe/London");
	    	put("B4U Movies","Europe/London");
	    	put("B4U Music","Europe/London");
	    	put("BBC Four","Europe/London");
	    	put("BBC HD","Europe/London");
	    	put("BBC News","Europe/London");
	    	put("BBC One","Europe/London");
	    	put("BBC Parliament","Europe/London");
	    	put("BBC Prime","Europe/London");
	    	put("BBC Three","Europe/London");
	    	put("BBC Two","Europe/London");
	    	put("BBC World News","Europe/London");
	    	put("Bravo","Europe/London");
	    	put("Carlton Television","Europe/London");
	    	put("CBBC","Europe/London");
	    	put("CBeebies","Europe/London");
	    	put("Challenge","Europe/London");
	    	put("Channel 4","Europe/London");
	    	put("Chart Show TV","Europe/London");
	    	put("Classic FM TV","Europe/London");
	    	put("Disney Cinemagic","Europe/London");
	    	put("Eurosport","Europe/London");
	    	put("FEM","Europe/London");
	    	put("Five","Europe/London");
	    	put("Five Life","Europe/London");
	    	put("Five US","Europe/London");
	    	put("ITV","Europe/London");
	    	put("ITV1","Europe/London");
	    	put("ITV2","Europe/London");
	    	put("ITV3","Europe/London");
	    	put("ITV4","Europe/London");
	    	put("Kerrang! TV","Europe/London");
	    	put("Kiss","Europe/London");
	    	put("Liberty TV","Europe/London");
	    	put("Living","Europe/London");
	    	put("Magic","Europe/London");
	    	put("MATV","Europe/London");
	    	put("MTV Base","Europe/London");
	    	put("MTV Dance","Europe/London");
	    	put("MUTV","Europe/London");
	    	put("Paramount Comedy","Europe/London");
	    	put("PlayJam","Europe/London");
	    	put("Pub Channel","Europe/London");
	    	put("Q TV","Europe/London");
	    	put("Red Hot TV","Europe/London");
	    	put("Revelation TV","Europe/London");
	    	put("rmusic TV","Europe/London");
	    	put("S4/C","Europe/London");
	    	put("S4C2","Europe/London");
	    	put("Scuzz","Europe/London");
	    	put("Sky Box Office","Europe/London");
	    	put("Sky Cinema","Europe/London");
	    	put("Sky Movies","Europe/London");
	    	put("Sky News","Europe/London");
	    	put("Sky Sports","Europe/London");
	    	put("Sky Travel","Europe/London");
	    	put("Sky1","Europe/London");
	    	put("Sky2","Europe/London");
	    	put("Sky3","Europe/London");
	    	put("Smash Hits","Europe/London");
	    	put("TCM","Europe/London");
	    	put("The Amp","Europe/London");
	    	put("The Box","Europe/London");
	    	put("Travel Channel","Europe/London");
	    	put("UK Entertainment Channel","Europe/London");
	    	put("UKTV Documentary","Europe/London");
	    	put("UKTV Drama","Europe/London");
	    	put("UKTV Food","Europe/London");
	    	put("UKTV G2","Europe/London");
	    	put("UKTV Gold","Europe/London");
	    	put("UKTV History","Europe/London");
	    	put("UKTV Style","Europe/London");
	    	put("ORF 1","WET");
	    	put("ORF 2","WET");
	    	put("BR","WET");
	    	put("Canvas/Ketnet","WET");
	    	put("één","WET");
	    	put("KanaalTwee","WET");
	    	put("VijfTV","WET");
	    	put("VT4","WET");
	    	put("VTM","WET");
	    	put("Danmarks Radio","WET");
	    	put("TV 2","WET");
	    	put("TV 3","WET");
	    	put("YLE","WET");
	    	put("Arte","WET");
	    	put("Canal Plus","WET");
	    	put("Fashion TV","WET");
	    	put("France 2","WET");
	    	put("France 3","WET");
	    	put("France 4","WET");
	    	put("France 5","WET");
	    	put("France Ô","WET");
	    	put("LCI","WET");
	    	put("M6","WET");
	    	put("Télétoon","WET");
	    	put("TF1","WET");
	    	put("TV5 Monde","WET");
	    	put("3sat","WET");
	    	put("BR-alpha","WET");
	    	put("Das Erste","WET");
	    	put("Deutsche Welle TV","WET");
	    	put("KIKA","WET");
	    	put("MDR","WET");
	    	put("NDR","WET");
	    	put("Phoenix","WET");
	    	put("ProSieben","WET");
	    	put("Radio Bremen","WET");
	    	put("RBB","WET");
	    	put("RTL Television","WET");
	    	put("SAT.1","WET");
	    	put("SWR","WET");
	    	put("Volksmusik TV","WET");
	    	put("WDR","WET");
	    	put("ZDF","WET");
	    	put("Canale 5","WET");
	    	put("RAI","WET");
	    	put("TVM","WET");
	    	put("TMF","CET");
	    	put("NTA","CET");
	    	put("NRK Super","CET");
	    	put("NRK1","CET");
	    	put("NRK2","CET");
	    	put("NRK3","CET");
	    	put("TV 2","CET");
	    	put("TV 2 Filmkanalen","CET");
	    	put("TV 2 Nyhetskanalen","CET");
	    	put("TV 2 Science Fiction","CET");
	    	put("TV 2 Sport","CET");
	    	put("TV 2 Zebra","CET");
	    	put("TVNorge","CET");
	    	put("Viasat 4","CET");
	    	put("TV 4","CET");
	    	put("TVN","CET");
	    	put("TVN Turbo","CET");
	    	put("TVP SA","CET");
	    	put("TVP1","CET");
	    	put("TVP2","CET");
	    	put("RTP Açores","WET");
	    	put("RTP África","WET");
	    	put("RTP Internacional","WET");
	    	put("RTP Madeira","WET");
	    	put("RTP N","WET");
	    	put("RTP1","WET");
	    	put("SIC","WET");
	    	put("SIC Comédia","WET");
	    	put("SIC Mulher","WET");
	    	put("SIC Notícias","WET");
	    	put("SIC Radical","WET");
	    	put("SIC Sempre Gold","WET");
	    	put("TV Cabo","WET");
	    	put("TVI","WET");
	    	put("Antena 3","CET");
	    	put("La Siete","CET");
	    	put("Telecinco","CET");
	    	put("TVE","CET");
	    	put("TV4","CET");
	    	put("Schweizer Fernsehen","CET");
	    	put("ANT1","EET");
	    	put("ERT","EET");
	    	put("Mega Channel","EET");
	    	put("KTN","EAT");
	    	put("Al Jazeera","Asia/Qatar");
	    	put("Al Alam","Asia/Tehran");
	    	put("Press TV","Asia/Tehran");
	    	put("Abu Dhabi TV","Asia/Dubai");
	    	put("Al Arabiyya","Asia/Dubai");
	    	put("AAG TV","PLT");
	    	put("Aaj TV","PLT");
	    	put("ARY Digital","PLT");
	    	put("ARY One World","PLT");
	    	put("ARY Shopping Channel","PLT");
	    	put("ARY Zouq","PLT");
	    	put("Dawn News","PLT");
	    	put("GEO Super","PLT");
	    	put("Geo TV","PLT");
	    	put("Indus Music","PLT");
	    	put("Indus News","PLT");
	    	put("Indus Vision","PLT");
	    	put("Kashish TV","PLT");
	    	put("KTN","PLT");
	    	put("News One","PLT");
	    	put("PTV Bolan","PLT");
	    	put("PTV Home","PLT");
	    	put("PTV News","PLT");
	    	put("QTV","PLT");
	    	put("Royal News","PLT");
	    	put("Doordarshan National Gujarat","IST");
	    	put("STAR Sports India","IST");
	    	put("Zee Gujarati","IST");
	    	put("Zee Movies","IST");
	    	put("Alpha TV GUJARATI","IST");
	    	put("Alpha TV PUNJABI","IST");
	    	put("ATN Aastha Channel","IST");
	    	put("CNBC TV18","IST");
	    	put("Doordarshan National","IST");
	    	put("Doordarshan News","IST");
	    	put("Doordarshan Sports","IST");
	    	put("ESPN India","IST");
	    	put("ETV Gujarati","IST");
	    	put("NDTV 24x7","IST");
	    	put("NDTV India","IST");
	    	put("Sab TV","IST");
	    	put("Sahara ONE","IST");
	    	put("Sanskar","IST");
	    	put("SET MAX","IST");
	    	put("Sony TV","IST");
	    	put("STAR Gold","IST");
	    	put("STAR News","IST");
	    	put("STAR Plus","IST");
	    	put("STAR Vijay","IST");
	    	put("SUN music","IST");
	    	put("SUN news","IST");
	    	put("SUN TV","IST");
	    	put("TEN Sports","IST");
	    	put("Zee Muzic","IST");
	    	put("Zee TV","IST");
	    	put("ZOOM","IST");
	    	put("Sirasa","IST");
	    	put("Swarnawahini","IST");
	    	put("TVRI","VST");
	    	put("RCTI","VST");
	    	put("CCTV","CTT");
	    	put("Channel [V]","CTT");
	    	put("Phoenix TV","CTT");
	    	put("TVB","CTT");
	    	put("TVBS","CTT");
	    	put("ESPN Hong Kong","CTT");
	    	put("STAR Movies","");
	    	put("ABC","CTT");
	    	put("ABS-CBN Broadcasting Company","CTT");
	    	put("ESPN Philippines","CTT");
	    	put("GMA","CTT");
	    	put("Studio 23","CTT");
	    	put("UNTV 37","CTT");
	    	put("Channel 5","Asia/Singapore");
	    	put("Channel 8","Asia/Singapore");
	    	put("Channel U","Asia/Singapore");
	    	put("STAR Sports S.E.A","Asia/Singapore");
	    	put("STAR Sports Singapore","Asia/Singapore");
	    	put("STAR Sports Taiwan","CTT");
	    	put("ESPN Taiwan","CTT");
	    	put("ESPN Asia","CTT");
	    	put("Star World","CTT");
	    	put("STAR Sports Asia","CTT");
	    	put("STAR Sports Hong Kong","CTT");
	    	put("Animax","JST");
	    	put("BS11","JST");
	    	put("CBC","JST");
	    	put("CTC","JST");
	    	put("Fuji TV","JST");
	    	put("MBS","JST");
	    	put("NHK","JST");
	    	put("NTV","JST");
	    	put("TBS","JST");
	    	put("Television Osaka","JST");
	    	put("Tokyo MX","JST");
	    	put("TV Asahi","JST");
	    	put("TV Tokyo","JST");
	    	put("TVA","JST");
	    	put("WOWOW","JST");
	    	put("ESPN Korea","ROK");
	    	put("EBS","ROK");
	    	put("KBS","ROK");
	    	put("SBS","ROK");
	    	put("Munhwa Broadcasting Corporation (MBC)","ROK");
	    	put("TV1","AET");
	    	put("Network Ten","AET");
	    	put("Nine Network","AET");
	    	put("Seven Network","AET");
	    	put("TVS Sydney","AET");
	    	put("TV One","NZ");
	    	put("TVNZ","NZ");    	
	    }
	};

}
